import 'react-image-gallery/styles/css/image-gallery.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'animate.css';

import 'react-toastify/dist/ReactToastify.css';

import 'nprogress/nprogress.css';
import '../styles/nprogress-custom.css';
import 'react-dropdown/style.css';
import '../styles/image-gallery.css';
import '../styles/slick.css';
import '../styles/masonry.css';
import '../styles/globals.css';

import {SessionProvider} from 'next-auth/react';
import Head from 'next/head';
import {Header} from '../components/Header';
import {Footer} from '../components/Footer';

import App, {AppContext} from 'next/app';

import Script from 'next/script';

import {Provider} from 'react-redux';
import store from '../store';
import categoryApi from '../service/categoryApi';
import {GetServerSideProps} from 'next';
import {useEffect, useMemo, useState} from 'react';
import {useRouter} from 'next/router';

import NProgress from 'nprogress';
import {getTokenSSRAndCSS} from '../helper';
import useGlobalState from '../state';

import Cookies from 'js-cookie';
import AdminSideBar from '../components/Admin/AdminSidebar';
import eventApi from '../service/eventApi';

// toast message
import {ToastContainer} from 'react-toastify';
import productApi from '../service/productApi';
import filterProductActive from '../helper/filterProductActive';

const MyApp = ({Component, pageProps, session}) => {
   const router = useRouter();
   const {categoryList, eventList, productGroupByNameList, token, userToken} = pageProps;

   const [, setToken] = useGlobalState('accessToken');
   const [, setCurrentUser] = useGlobalState('currentUser');

   // set global state

   useMemo(() => {
      setToken(pageProps.token);
      setCurrentUser(pageProps.userInfo);
   }, []);

   // nprogress configure
   useEffect(() => {
      NProgress.configure({showSpinner: false});
      router.events.on('routeChangeStart', () => {
         NProgress.set(0.5);
         NProgress.start();
      });
      router.events.on('routeChangeComplete', () => {
         NProgress.done();
      });
      router.events.on('routeChangeError', () => {
         NProgress.done();
      });
   }, []);

   const isAdminPage = useMemo(() => {
      return router.pathname.indexOf('admin') >= 0;
   }, [router.pathname]);

   return (
      <SessionProvider session={session}>
         <Provider store={store}>
            <Head>
               <title>Cocozzi</title>
               <meta name='description' content='Generated by create next app' />
               <link rel='icon' href='/favicon.ico' />
            </Head>
            <Script src='https://sp.zalo.me/plugins/sdk.js'></Script>

            <Header
               categoryList={categoryList}
               eventList={eventList}
               productGroupByNameList={productGroupByNameList}></Header>
            <div className=''>
               {isAdminPage && <AdminSideBar />}
               <Component {...pageProps} />
            </div>
            {router.pathname.indexOf('shop') < 0 && <Footer></Footer>}

            <ToastContainer
               position='bottom-right'
               autoClose={5000}
               hideProgressBar={false}
               newestOnTop={false}
               closeOnClick
               rtl={false}
               pauseOnFocusLoss
               pauseOnHover
               theme='dark'
               className='toastify-font-dth'
            />
         </Provider>
      </SessionProvider>
   );
};

MyApp.getInitialProps = async (appContext: AppContext) => {
   let appProps, categoryList, eventList, productGroupByNameList;
   const [token, userToken] = getTokenSSRAndCSS(appContext.ctx);
   const userId = userToken?.data._id;
   try {
      appProps = await App.getInitialProps(appContext);

      const categoryPos = categoryApi.getAllCategory();
      const eventPos = eventApi.getAllEvent();
      const productGroupNamePos = productApi.getAllProductByName();

      const [categoryRes, eventRes, productGroupNameRes] = await Promise.all([
         categoryPos,
         eventPos,
         productGroupNamePos,
      ]);

      categoryList = categoryRes?.data?.data?.filter(
         (cate) =>
            cate.status == true &&
            (cate?.description?.indexOf('-category-for-promo') < 0 || !cate?.description)
      );
      eventList = eventRes?.data?.data.filter((event) => event.status == true);
      const productByGroupNameData = productGroupNameRes?.data?.data;

      productGroupByNameList =
         productByGroupNameData?.length > 0 ? filterProductActive(productByGroupNameData) : [];
   } catch (error) {}

   return {
      pageProps: {
         ...appProps.pageProps,
         categoryList: categoryList || [],
         eventList: eventList || [],
         productGroupByNameList: productGroupByNameList || [],
         token: token,
         userToken: userToken,
      },
   };
};

export default MyApp;
